services:
  - type: web
    name: auth-module
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8081
      - key: DB_HOST
        value: your-database-host
      - key: DB_USER
        value: your-db-user
      - key: DB_PASS
        sync: false  # Будет задано в панели Render
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false